- name: variables from prompt
  hosts: local
  connection: local #ansible is connecting to local host
  vars_prompt:
  - name: username
    prompt: What is your username?
    private: false
  - name: password
    prompt: What is your password?
    private: true
  tasks:
  - name: print credentials
    ansible.builtin.debug:
      msg: "Hello, Username is: {{ username }}, Password is: {{ password }}"